### ISSUE TITLE
amt102-v is it CAN BUS??????

### ISSUE THREAD

**Issue by ctm6100** [PolyU-Robocon/IGGG-Connector-Standard#2]
ng is ABI encoder???????
https://github.com/PolyU-Robocon/IGGG-Connector-Standard/tree/main/CAN%20Bus#can-bus-to-amtseries-iggg-can-amt102-v

**Comment by ctm6100** [comment]
![image](https://user-images.githubusercontent.com/45313904/169816195-b6fa0b75-59e5-4912-806f-c6e654974486.png)

**Comment by SamsonChau** [comment]
This is just an ABI encoder not can bus
